- name: Ensure python3-debian is installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ kea_prereq_packages }}"
  become: true

- name: Add cloudsmith apt repo
  when: kea_version == (source.name | split('-') | last)
  ansible.builtin.deb822_repository:
    name: "{{ source.name }}"
    types: "{{ source.types }}"
    uris: "{{ source.uris }}"
    suites: "{{ source.suites }}"
    components: "{{ source.components }}"
    signed_by: "{{ source.signed_by }}"
  loop: "{{ _kea_apt_sources }}"
  loop_control:
    loop_var: source
  become: true

# Using apt so we can force cache update, non apt systems will need a separate task
- name: Update apt cache and install required packages
  ansible.builtin.apt:
    name: "{{ kea_install_packages }}"
    state: present
    update_cache: true
  become: true
